#######################################################
# Enclosure config for PCB
#
# The dimensions of the enclusure depend on the
# parameters of the PCB
#
# Optional features:
#   - mount tabs
#   - ventilation holes
#   - holes for connectors (rectangular, circular, sensor)
#######################################################

[box]
pcb_length = 58.42
pcb_width = 33.02
pcb_thick = 1.6
pcb_hole_diameter = 3.5
pcb_hole_corner_dist = 5
pcb_lid_dist = 2.0
inner_depth = 19.0
wall = 1.2
rounding_vertical_edges = true
rounding_top_edges = false
rounding_radius = 1.5
gap_x = 0.2              # Gaps between PCB and box
gap_y = 0.2
gap_z = 0.2             # Gap between PCB and lid
tolerance = 0.20        # To reduces the size of the lid

[perforation]
top_perforation = true
x_side_perforation = true
y_side_perforation = true
vent_hole_diameter = 3.5
grid_density = 0.60

[circular_connector]
circular = true
diameter = 10.0
from_pcb_plane = 6.5    # distance of center from PCB plane
from_pcb_corner = 10.0  # distance from bottom left corner of PCB
faces = '>X'            # '>X'|'<X'|'>Y'|'<Y'

[rectangular_connector]
rectangular = false
height = 13.0
width = 7.0
from_pcb = 10.5         # center line distance form PCB
from_pcb_corner = 20    # distance from bottom left corner of PCB
faces = '<Y'            # '>X' | '<X' | '>Y' | '<Y'

[sensor_hole_at_top]
sensor = true
hole_diameter = 10.0
distance_from_y_edge = 7.5
distance_from_x_edge = 12.5

[lid_bolt]
head = 'socket'         # 'socket' | 'flat'
bolt_diameter = 2.7
head_diameter = 5.5
head_length = 2.0
nr = 2                  # 2 | 4
mirror = true

[mounting]
mounts = true
bolt_diameter = 3.0
